### ISSUE TITLE
VSCode Audio Initially On

### ISSUE THREAD

**Issue by tom131313** [wpilibsuite/2025Beta#18]
My first 2025 project caused VSCode to gurgle every couple of seconds. It finally stopped for the most part and I suspect it was from the large number of errors I was fixing as I was manually converting a 2024 project to 2025 (mostly the ` imports for Measure<Time>`, etc.).

Changing the VSCode setting `accessibility.signalOptions.volume`  to `0` silenced the noisy VSCode.

If I'm the only person with this issue, then forget it. If others experience the VSCode sounds, then I recommend a comment being added to the installation documentation.

**Comment by sciencewhiz** [comment]
Can you post a link to the project that you imported?

**Comment by tom131313** [comment]
I created a new Java example project `eventloop`. I deleted the Java files and copied into the project the Java files from https://github.com/tom131313/Example-LED . I deleted my copies of the WPILib Java files that are in 2025 (but weren't in 2024 - those associated with LED addressable buffer, etc.). I changed the `Measure<Time>` to `Time` and fixed all the `imports` that were no longer needed for my 2024 inclusions and now needed to reference the 2025 WPILib.

Throughout that process I heard the noises and had no idea what caused them. After the project was working perfectly and I closed VSCode the gurgling stopped. It has not restarted. Many events in VSCode cause sounds to play (at least it was no longer every 2 or 3 seconds) so I figured out the easy way to silence them is set the volume to 0.

**Comment by ThadHouse** [comment]
It looks like this is a new setting added in the 1.87 release of VS Code. 

https://code.visualstudio.com/updates/v1_87#_accessibility

**Comment by rzblue** [comment]
It looks like all of the signal sounds and announcements are off by default.

**Comment by tom131313** [comment]
There is a Screen Reader Optimized area at the bottom right of the screen that appears briefly and randomly as far as I can tell. It may show after I do some typing but if I type exactly the same again it doesn't show. I notice several issues with the Accessibility have been reported. I can toggle it with Shift+Alt+F1 but what makes it appear on its own I have no idea. That may control the sounds.

I didn't knowingly turn on accessibility but I'm willing to be responsible for "User Error" and close this. Thanks.

**Comment by sciencewhiz** [comment]
Do you perhaps have other windows accessibility set that VS Code is inheriting?

**Comment by tom131313** [comment]
I'm sure I figured out what my error was. The VS Code initially displays the `Screen Reader Optimized` at the bottom of the screen. If I click on it, it shows the options for `Are you using a screen reader to operate VS Code?` They are `Yes` (the default), `No`, `X` (close and implied `Yes`), and `Enter` implied `Yes`. If I don't click `No`, VS Code gurgles every four seconds. I'm sure I thought hitting `X` to close was the safe thing to do to keep things as they were. I was wrong - `X` is `Yes` and sounds abound.

Setting the volume to 0 is highly effective to silence the many sounds no matter what I accidentally touch or can't track down in settings to turn off.

Windows 11 has many settings for Accessibility. I have a couple of them on such as show scroll bars and show circle touch screen spot. I couldn't find documentation on any tie between Windows and VSCode but anything is possible.

**Comment by sciencewhiz** [comment]
https://code.visualstudio.com/docs/editor/accessibility#_screen-reader-mode
