### ISSUE TITLE
Shuffleboard doesn't display fields on code generated tabs

### ISSUE THREAD

**Issue by jwt388** [wpilibsuite/2025Beta#39]
Shuffleboard tabs and layouts created in Java code are not properly displayed. In most cases a blank tab is created, even though the entries show up in the source list under the Shuffleboard section and tab name and can be manually dragged onto a tab. Sometimes only a subset of the entries shows up on the tab. Other times some entries are displayed with the wrong layout or widget. This issue was seen when running on the RoboRio and in simulation.

This behavior was seen when porting code from 2024 but was also reproduced by creating a new 2025 project from a template and just adding the following line to the RobotContainer constructor.
    Shuffleboard.getTab("Numbers").add("Pi", 3.14);

When Shuffleboard 2024 is run with 2025 code, all fields are displayed properly.

**Comment by sciencewhiz** [comment]
I believe this is addressed by https://github.com/wpilibsuite/shuffleboard/pull/815

**Comment by rzblue** [comment]
Fixed in v2025.1.1-beta-2
