### ISSUE TITLE
SparkMaxRelativeEncoderSim iterate not properly setting the position

### ISSUE THREAD

**Issue by trindels** [wpilibsuite/2025Beta#43]
**Describe the bug**
SparkMaxRelativeEncoderSim.iterate( velocity, dt ) is setting Position value to match the Velocity value scaled to the dt.

**To Reproduce**

```python
import rev
import wpilib
import wpimath.units
import wpimath.system.plant

def __init__(self):
    self.controller = wpilib.XboxController(1)
    self.motor = rev.SparkMax( 1, rev.SparkMax.MotorType.kBrushless )
    self.simMotor = rev.SparkMaxSim( self.motor, wpimath.system.plant.DCMotor.NEO(1) )

def periodic(self):
    self.motor.set( self.controller.getLeftX() )

def simulationPeriodic(self):
    maxRpm = wpimath.units.radiansToRotations( wpimath.system.plant.DCMotor.NEO(1).freespeed ) * wpimath.units.kSecondsPerMinute
    rpm = maxRpm * self.motor.get()
    self.simMotor.getRelativeEncoderSim().iterate( rpm, 0.02 )

    print( self.simMotor.getRelativeEncoderSim().getPosition(), self.simMotor.getRelativeEncoderSim().getVelocity() )
```

**Expected behavior**
Position should be increasing incrementally based on the velocity.  Position = Position + ( Velocity / 60 * dt )

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: Windows 11
 - OS Language: English
 - Project Information: VSCode, Python 3.13, Simulation Environment

**roboRIO (please complete the following information if applicable):**
 - roboRIO 1 or 2?:  N/A
 - Image version: [Use the roboRIO imaging tool or the WPILib team number setter to determine the image version]

**Additional context**

**Comment by jfabellera** [comment]
This will be fixed along with #44 in the next release.
