### ISSUE TITLE
SparkMaxRelativeEncoderSim and SparkMaxAbsoluteEncoderSim do not default Position and Velocity Conversion Factor to 1 (as documented)

### ISSUE THREAD

**Issue by trindels** [wpilibsuite/2025Beta#44]
**Describe the bug**
SparkMaxRelativeEncoderSim.iterate and SparkMaxAbsoluteEncoderSim.iterate do not work until you properly use setPositionConversionFactor(1) and setVelocityConversionFactor(1).  Documentation indicates that 1 should be the default value.  Currently, default value is 0.

**To Reproduce**

```python
import rev
import wpilib
import wpimath.units
import wpimath.system.plant

def __init__(self):
    self.controller = wpilib.XboxController(1)
    self.motor = rev.SparkMax( 1, rev.SparkMax.MotorType.kBrushless )
    self.simMotor = rev.SparkMaxSim( self.motor, wpimath.system.plant.DCMotor.NEO(1) )

def periodic(self):
    self.motor.set( self.controller.getLeftX() )

def simulationPeriodic(self):
    maxRpm = wpimath.units.radiansToRotations( wpimath.system.plant.DCMotor.NEO(1).freespeed ) * wpimath.units.kSecondsPerMinute
    rpm = maxRpm * self.motor.get()
    self.simMotor.getRelativeEncoderSim().iterate( rpm, 0.02 )
    self.simMotor.getAbsoluteEncoderSim().iterate( rpm, 0.02 )

    print( self.simMotor.getRelativeEncoderSim().getPosition(), self.simMotor.getRelativeEncoderSim().getVelocity() )
    print( self.simMotor.getAbsoluteEncoderSim().getPosition(), self.simMotor.getAbsoluteEncoderSim().getVelocity() )
```

**Expected behavior**
Position and Velocity should properly be the output.
Position += Velocity * dt

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: Windows 11
 - OS Language: English
 - Project Information: VSCode, Python 3.13, Simulation Environment

**roboRIO (please complete the following information if applicable):**
 - roboRIO 1 or 2?:  N/A
 - Image version: [Use the roboRIO imaging tool or the WPILib team number setter to determine the image version]

**Additional context**

**Comment by jfabellera** [comment]
Thanks for the report, this will be fixed in the next release.
