### ISSUE TITLE
SimGUI Window menu empty

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/2025Beta#48]
**Describe the bug**
When the Window menu at the the top of SimGUI is clicked it just puts a small black box on the screen. I suspect this is an indication that there are no actual entries on that menu.

**To Reproduce**
1. Create a project: I used Example|Java|ArcadeDrive
2. Simulate Robot Code

 - Link to code (if applicable):

**Expected behavior**
Clicking Window menu displays list of choices.

**Screenshots**
![Image](https://github.com/user-attachments/assets/a7c861d8-0057-4aad-8de4-b492678f2743)

**Desktop (please complete the following information if applicable):**
 - OS: Windows 11, Linux Ubuntu 22.04
 - OS Language: English
 - Project Information: for Linux: WPILib Information:
Project Version: 2025.1.1-beta-1
VS Code Version: 1.94.2
WPILib Extension Version: 2025.1.1-beta-1
C++ Extension Version: 1.22.9
Java Extension Version: 1.36.2024092708
Java Debug Extension Version: 0.58.2024090204
Java Dependencies Extension Version 0.24.0
Java Version: 17
Java Location: /home/hauser/wpilib/2025/jdk
Vendor Libraries:
    WPILib-New-Commands (1.0.0)

**roboRIO (please complete the following information if applicable):**
 - roboRIO 1 or 2?: N/A

**Additional context**

**Comment by GrahamSH-LLK** [comment]
Can reproduce on macOS
![Image](https://github.com/user-attachments/assets/621fb7d4-9474-435e-bac4-89f1663f15e9)

**Comment by chauser** [comment]
I revisited a 2024 simulation last night and discovered this bug was present then as well.

**Comment by sciencewhiz** [comment]
This should be fixed in beta 3
