### ISSUE TITLE
Epilogue trouble annotating inner classes

### ISSUE THREAD

**Issue by PeterG-08** [wpilibsuite/2025Beta#54]
**Describe the bug**
I have a class being annotated by the Epilogue `@Logged` annotation. The class contains an inner record, that's also being annotated with `@Logged`. When I try building the robot code the build fails as Epilogue is generating a folder whose name matches the name of the outer class that contains the inner record.

**To Reproduce**
1. Create a new class and annotate it with `@Logged`.
2. Create an inner class in that class and also annotate it with `@Logged`.
3. Build robot code.

 - Link to code (if applicable):
 -[VisionPoseEstimator.java](https://github.com/Team334/SwerveBase-CTRE/blob/f5a27fee022a9ee926b0c2dc07bd709e846a477f/src/main/java/frc/robot/utils/VisionPoseEstimator.java)

**Expected behavior**
The build will be successful and Epilogue can handle generating its code for the outer and inner annotated classes.

**Screenshots**
![Image](https://github.com/user-attachments/assets/f3d35ba0-95e2-434a-9b33-06e135e1719b)
![Image](https://github.com/user-attachments/assets/a3f90e40-4d9d-4678-a0dc-800ddd348f92)

**Desktop (please complete the following information if applicable):**
 - Windows 10
 - English
 - WPILib Information:
Project Version: 2025.1.1-beta-2
VS Code Version: 1.94.2
WPILib Extension Version: 2025.1.1-beta-1
C++ Extension Version: 1.22.9
Java Extension Version: 1.36.2024092708
Java Debug Extension Version: 0.58.2024090204
Java Dependencies Extension Version 0.24.0
Java Version: 17
Java Location: C:\Users\Public\wpilib\2025\jdk
Vendor Libraries:
    DogLog (2025.1.1)
    CTRE-Phoenix (v6) (25.0.0-beta-3)
    photonlib (v2025.0.0-beta-5)
    WPILib-New-Commands (1.0.0)

**roboRIO (please complete the following information if applicable):**
I'm just building on my computer to test in sim.

**Additional context**

**Comment by sciencewhiz** [comment]
This should be fixed in beta 3
