### ISSUE TITLE
REVLib C++: simulating Spark devices doesn't change position or velocity

### ISSUE THREAD

**Issue by Liam-Stow** [wpilibsuite/2025Beta#55]
**Describe the bug**
In REVLib C++, simulating a Spark using SparkFlexSim or SparkMaxSim results in no change to the reported position or velocity of the device.

**To Reproduce**
Error is present when simulating this project: https://github.com/Liam-Stow/2025-spark-sim/blob/main/src/main/cpp/Robot.cpp
As a quick reference:
```cpp
void Robot::TeleopInit() {
  m_flex.Set(1.0);
  m_max.Set(1.0);
}

void Robot::SimulationPeriodic() {
  const units::volt_t busVoltage = 12_V;
  const units::second_t dt = 20_ms;

  // Sim Spark MAX + NEO
  units::volt_t neoVoltage = m_maxSim.GetAppliedOutput() * busVoltage;
  m_neoFlywheelSim.SetInputVoltage(neoVoltage);
  m_neoFlywheelSim.Update(dt);
  units::revolutions_per_minute_t neoVelocity = m_neoFlywheelSim.GetAngularVelocity() * GEARING;
  m_maxSim.iterate(neoVelocity.value(), busVoltage.value(), dt.value());

  // Sim Spark Flex + Vortex
  units::volt_t flexVoltage = m_flexSim.GetAppliedOutput() * busVoltage;
  m_vortexFlywheelSim.SetInputVoltage(flexVoltage);
  m_vortexFlywheelSim.Update(dt);
  units::revolutions_per_minute_t flexVelocity = m_vortexFlywheelSim.GetAngularVelocity() * GEARING;
  m_flexSim.iterate(flexVelocity.value(), busVoltage.value(), dt.value());
}
```

**Expected behavior**
when the robot state in sim gui is set to enabled, the spark devices should gain a positive velocity and change position over time. Applied output, motor current and setpoint should also change.

**Actual behavior**
position, velocity, applied output and motor current all stay at zero. The setpoint does change as expected.

**Screenshots**
![Image](https://github.com/user-attachments/assets/602dfb4b-9047-45e1-a4c4-0ec81a2f00aa)

As a reference, this is what happens when the equivalent code in Java in simulated:
(A little strange that the velocity jumps at the beginning, but that seems like a different issue.)
![Image](https://github.com/user-attachments/assets/6b4c5120-6813-4f36-91c4-5bf60d067e3f)
The above java example uses this code:
```java
  @Override
  public void teleopInit() {
    max.set(1.0);
    flex.set(1.0);
  }

  @Override
  public void simulationPeriodic() {
    double busVoltage = 12;
    double dt = 0.02;

    // Sim Spark MAX + NEO
    double neoVoltage = maxSim.getAppliedOutput() * busVoltage;
    neoFlywheelSim.setInputVoltage(neoVoltage);
    neoFlywheelSim.update(dt);
    double neoVelocity = neoFlywheelSim.getAngularVelocityRPM() * GEARING;
    maxSim.iterate(neoVelocity, busVoltage, dt);

    // Sim Spark Flex + Vortex
    double vortexVoltage = flexSim.getAppliedOutput() * busVoltage;
    vortexFlywheelSim.setInputVoltage(vortexVoltage);
    vortexFlywheelSim.update(dt);
    double vortexVelocity = vortexFlywheelSim.getAngularVelocityRPM() * GEARING;
    flexSim.iterate(vortexVelocity, busVoltage, dt);
  }
```

**Desktop:**
 - OS: Windows 11
 - OS Language: English
 - Project Information: WPILib Information:
    - Project Version: 2025.1.1-beta-2
    - VS Code Version: 1.95.3
    - WPILib Extension Version: 2025.1.1-beta-2
    - C++ Extension Version: 1.22.9
    - Java Extension Version: 1.36.2024092708
    - Java Debug Extension Version: 0.58.2024090204
    - Java Dependencies Extension Version 0.24.0
    - Java Version: 17
    - Java Location: C:\Users\Public\wpilib\2025\jdk
    - Vendor Libraries:
      - REVLib (2025.0.0-beta-3)

**Additional context**
- This behavior was also seen in REVLib beta 2. 
- REVLib beta 3 was installed through https://github.com/REVrobotics/REV-Software-Binaries/releases/tag/revlib-2025.0.0-beta-3 not through the inbuilt WPI vendor dependency manager.
- Attempting to "bypass" the iterate() function and instead calling m_flexSim.SetVelocity() or m_flexSim.SetPosition() directly results in the same issue: no change to the device velocity in sim gui.
- There is also no change to the various encoder devices in sim gui ("SPARK MAX [1] RELATIVE ENCODER", etc)

**Comment by jfabellera** [comment]
This looks to be an issue with the flywheel sim or how it is used.

When I debug this program, the values for `neoVelocity` and `flexVelocity` are 0 (regardless of what robot state I select)

![Image](https://github.com/user-attachments/assets/27d8f210-f9c3-4ccd-a84e-d4043aaa911c)

If I replace the variable in `iterate()` with a number, it looks to behave correctly.

![Image](https://github.com/user-attachments/assets/adc6dd30-1d0c-4c03-b42a-8c1fdee1b996)

**Comment by Liam-Stow** [comment]
Thanks for looking into the issue.
Interestingly, that is not the behavior I am seeing when running with constant numbers in iterate(). This is the simplest I can think to make it, and I still don't see any movement on the sim:
![Image](https://github.com/user-attachments/assets/b7cffa01-0505-406b-a08a-8a033f616f97)

I can also bypass iterate() entirely by running SetVelocity() and SetPosition() and the sim still stays at all zero (except the setpoint, which does change to match any spark.Set() calls)
![Image](https://github.com/user-attachments/assets/b81dc50c-ceaf-4da1-8a0e-300051690c59)

**Comment by Liam-Stow** [comment]
The core of this issue seems to be fixed in REVLib beta 4. Iterate() now successfully changes the sim position and velocity 🙂.
However, applied output still stays at zero (unlike the Java version, where it changes accordingly after any spark.Set() calls or closedLoopController.SetReference() calls). Fixing that to behave the same as it does in the Java version should enable the use of WPI mechanism simulation like in my example code linked above.

Simulated motor current also still has some strange behavior. Rather than spiking during accelerations and then dropping back to zero as the motor reaches its max velocity, the current instead stays at its maximum. I see my simulated flex+vortex sitting at -211 Motor Current in the sim with a 1.0 duty cycle, whereas with the equivalent Java code it hits that value then decreases back to 0.

Thanks for your work!
