### ISSUE TITLE
roboRIO Team Number Setter doesn't show proper status of NI System Web Server

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/2025Beta#71]
**Describe the bug**
In the roboRIO Team Number Setter tool, after clicking Disable Web Server and refreshing status the web server is still reported as Enabled, although in fact its processes have been killed and it is no longer accessible. 

**To Reproduce**
1. Use the roboRIO Team Number Setter tool to disable the web server of a roboRIO
2. Use the refresh status button in the tool and observe that the web server is shown as enabled
3. Attempt to connect to the web server and see that the browser says it's unreachable
4. SSH to the rio and us `ps a` to observe that the web server processes are not present

**Expected behavior**
The status should be accurate.

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: Team Number Setter tool running on Windows 11
 - OS Language: English
 - Project Information: N/A

**roboRIO (please complete the following information if applicable):**
 - roboRIO 1 or 2?: only tested on a rio 1
 - Image version: FRC_roboRIO_2025_v1.0

**Additional context**
In my opinion, it would be very nice if disabling the system web server from the Team Number Setter tool was persistent across boots. I expect that for many teams using roboRIO 1 this year it is going to be necessary to disable the web server to have enough memory available for their robot programs. Since the web server provides no useful functionality (the one thing I might use it for -- to control the "Disable RT Startup App" setting -- doesn't work), I really don't see any downside to persistently disabling it from the Team Number Setter tool.

**Comment by chauser** [comment]
My remark above about wanting the disable status of the web server to persist across boots seems to already be the behavior. Though I could have sworn yesterday that it wasn't. And the remarks in the docs page for disabling the web server also suggest that it doesn't work sometimes.
I'm investigating both of these behaviors (wrong status and non-persistence) further and will report here when I know more.

**Comment by chauser** [comment]
The wrong-status problem likely stems from PR https://github.com/wpilibsuite/allwpilib/pull/7284 -- in particular line 149, which should be 
`exitCode = ssh_channel_get_exit_status(channel);` 
instead of 
`ssh_channel_get_exit_status(channel);`

**Comment by sciencewhiz** [comment]
The fix is included in beta 3
