### ISSUE TITLE
roboRIO Imaging Tool can't connect roboRIO if web server is disabled

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/2025Beta#74]
This isn't exactly a bug, but it is an issue that some might encounter so I want to document a workaround.

~~After imaging a roboRIO 1 with the 2025 beta image (using the 2025 roboRIO Imaging Tool) when I try to re-image it with the 2024 roboRIO Imaging Tool the tool does not discover the roboRIO no matter how many times I re-scan. The connection is USB. It has occurred multiple times for me.~~

If you disable the roboRIO system web server (e.g. if your code needs more memory than is available with it running) the robotRIO Imaging Tool is unable to see the roboRIO.

An easy workaround is to boot the roboRIO into "safe" or "recovery" mode: press and hold the RESET button for about 5 seconds -- until the status light flashes. It will take a few more seconds for the roboRIO to finish booting. After that the  imaging tool discovers the roboRIO and the imaging process works as normal.

Alternatively, use the roboRIOTeamNumberSetter tool from the WPILib "Start Tool" menu to re-enable the web server.

**Comment by ThadHouse** [comment]
You’re not disabling the web server, right? Disabling that breaks the imaging tool.

**Comment by chauser** [comment]
I probably was! (because our code doesn't fit otherwise) I had no idea of that dependency. Good to know and I'm changing the title and content to reflect that.
