### ISSUE TITLE
Build failure when using Spotless and Epilogue

### ISSUE THREAD

**Issue by crschardt** [wpilibsuite/2025Beta#75]
**Describe the bug**
After configuring a project to use Spotless and then enabling logging with Epilogue, running `./gradlew build` fails and displays the following error:

```
> Task :spotlessJavaCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessJavaCheck'.
> The following files had format violations:
      bin\generated-sources\annotations\edu\wpi\first\epilogue\Epilogue.java
...
``` 
Running `./gradlew spotlessApply` after the failure allows the build to succeed, but the failure will reoccurs after code changes cause Epilogue to recreate the generated files.

**To Reproduce**
1. Configure project to use spotless per the instructions in the WPILib docs
2. Mark one or more classes with the Epilogue `@Logged` annotation
3. Run `./gradlew build`

**Expected behavior**
Running `./gradlew build` should not fail. In addition, the directory where the error occurs is hidden and doesn't appear in the VSCode Explorer, which makes the error even more confusing to debug.

**Desktop (please complete the following information if applicable):**
 - OS: Windows 11
 - OS Language: English
 - Project Information: WPILib Information:
Project Version: 2025.1.1-beta-2
VS Code Version: 1.95.3
WPILib Extension Version: 2025.1.1-beta-2
C++ Extension Version: 1.22.9
Java Extension Version: 1.36.2024092708
Java Debug Extension Version: 0.58.2024090204
Java Dependencies Extension Version 0.24.0
Java Version: 17
Java Location: C:\Users\Public\wpilib\2025\jdk
Vendor Libraries:
    photonlib (v2025.0.0-beta-6)
    REVLib (2025.0.0-beta-3)
    Studica (2025.1.1-beta-4)
    WPILib-New-Commands (1.0.0)

**Additional context**
The build failure can be avoided by updating the spotless section of `build.gradle` to exclude the bin directory and subdirectories.
```
spotless {
    java {
        target fileTree('.') {
            include '**/*.java'
            exclude '**/build/**', '**/build-*/**', '**/bin/**'
        }
        toggleOffOn()
        googleJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
...
```

**Comment by ThadHouse** [comment]
We don’t include spotless in projects by default, mainly for reasons similar to this. There’s no way rt can ensure the generated code matches the format the formatter is looking for. 

The bin folder is created by vscode, we don’t can’t roll it. And likely spotless is just globbing everything, and not including that in its default config. Not really something we can fix.

**Comment by crschardt** [comment]
You provide instructions for adding spotless in the documentation and you could update the documented spotless settings to exclude the bin directory as mentioned in the bug report.

**Comment by agasser** [comment]
Spotless is working in [my project](https://github.com/STMARobotics/frc-7028-2024/blob/cc4d8690d198df7ecf7246d97163a3aba4ee3661/build.gradle#L106) using Epilogue with Beta 2. My configuration is different:

```
spotless {
  java {
    importOrder()
    removeUnusedImports()
    eclipse().configFile('.vscode/eclipse-formatter.xml')
  }
}
```

You should be able to see the [GitHub action](https://github.com/STMARobotics/frc-7028-2024/actions/workflows/spotless.yml) I have set up that runs `gradlew spotlessCheck`.

**Comment by agasser** [comment]
Oh, dug a little deeper and see your solution is to exclude the `bin` dir. That makes perfect sense.
