### ISSUE TITLE
EEPROM faults and temperature cutoff fault LED pattern for SPARK Flex at robot code startup

### ISSUE THREAD

**Issue by JochemvdBroek** [wpilibsuite/2025Beta#77]
During one evening of testing, it occurred at two different moments that a single Spark Flex (each time it was a different motor) on our drivetrain showed the LED status pattern for temperature cutoff fault (orange green blinking). A current limit of 70 amps was present, no significant load was put on the motors during testing and they did not feel hot when touched. 

The motor that showed the led error code did not respond when we enabled the robot, but the other motors did. 

When we viewed the status of the Spark Flex in the REV Hardware Client we saw the following error codes:

![Image](https://github.com/user-attachments/assets/7823ac46-d367-4108-bba5-df1371cc1d04)

The first time the led status code occurred we were able to fix it by re-installing the current version of the firmware on the Spark Flex. The second time the led status code went away after a power cycle, after which the motor responded as usual again.

Both times the temperature fault LED pattern started showing about a minute after powering on the robot. So we suspect it has something to do with the configuration/initialization of the Spark Flexes at the start of the code. 

We used the following software versions:
- REVLib: REVLib-2025.0.0-beta-2
- Spark Flex firmware: 25.0.0-prerelease.4
- WPILib: 2025.1.1-beta-1

**Comment by jfabellera** [comment]
This will be fixed in the next release
