### ISSUE TITLE
Self Test in Phoenix Tuner X always displays the encoder direction in clockwise positive

### ISSUE THREAD

**Issue by Gold856** [wpilibsuite/2025Beta#8]
When using the Self Test feature in Phoenix Tuner X to view the position on a CANCoder, the direction is always clockwise positive, even if the CANCoder is configured to be counterclockwise positive.
![Image](https://github.com/user-attachments/assets/0cd26cba-8cc5-47bb-9710-f7dc29e9c7cf)

![Image](https://github.com/user-attachments/assets/9e211afc-ca90-4d6d-9dfe-dec3c38e47d9)

**Comment by bhall-ctre** [comment]
This is fixed in beta-2.
